version: '3'
services:
  pebblehost_bot:
    container_name: pebblehost_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run build && node dist/bot.js"